// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSDWXx9DEkhCLKxFEeC_zW3vKTSYVEzw',
    appId: '1:571814077535:web:d87e22b78f2dd117ade7ea',
    messagingSenderId: '571814077535',
    projectId: 'final-exam-fc880',
    authDomain: 'final-exam-fc880.firebaseapp.com',
    storageBucket: 'final-exam-fc880.appspot.com',
    measurementId: 'G-JTD0DSG5SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNOFtvWheEIxiCUJGgDvgHmkdRPsUOSw',
    appId: '1:571814077535:android:8c92a533a9d7b0ddade7ea',
    messagingSenderId: '571814077535',
    projectId: 'final-exam-fc880',
    storageBucket: 'final-exam-fc880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnSYl5MriKDpQwZrzOjh_MOVS5967zhwQ',
    appId: '1:571814077535:ios:1e12065c5cf0f844ade7ea',
    messagingSenderId: '571814077535',
    projectId: 'final-exam-fc880',
    storageBucket: 'final-exam-fc880.appspot.com',
    iosBundleId: 'com.example.examFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnSYl5MriKDpQwZrzOjh_MOVS5967zhwQ',
    appId: '1:571814077535:ios:1e12065c5cf0f844ade7ea',
    messagingSenderId: '571814077535',
    projectId: 'final-exam-fc880',
    storageBucket: 'final-exam-fc880.appspot.com',
    iosBundleId: 'com.example.examFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSDWXx9DEkhCLKxFEeC_zW3vKTSYVEzw',
    appId: '1:571814077535:web:0f5b3fd953d93444ade7ea',
    messagingSenderId: '571814077535',
    projectId: 'final-exam-fc880',
    authDomain: 'final-exam-fc880.firebaseapp.com',
    storageBucket: 'final-exam-fc880.appspot.com',
    measurementId: 'G-MDDVMW2649',
  );
}
